### ISSUE TITLE
Restructure the folder

### ISSUE THREAD

**Issue by macaroni7** [mintlayer/mojito_mobile_wallet#92]
## Context

The current root folder contains all the subfolders related the product development, such as `components`, `screens` etc, this makes it a bit hard to maintain the features.

```
├── assets
│   └── fonts
├── blue_modules
│   ├── aezeed
│   │   └── src
│   ├── bc-bech32
│   │   └── dist
│   ├── bc-ur
│   │   └── dist
│   └── ur
├── class
│   └── wallets
├── components
│   └── addresses
├── constants
├── core
│   └── react-native-tor
├── helpers
├── img
│   ├── addWallet
│   │   └── btcBig
│   ├── bottomTab
│   ├── circle_logo
│   ├── header_logo
│   ├── intro
│   ├── mshelp
│   ├── qr_code
│   └── splash
├── loc
├── models
├── screen
│   ├── NativeAssets
│   ├── introduction
│   ├── lnd
│   ├── receive
│   ├── send
│   ├── settings
│   ├── transactions
│   └── wallets
├── scripts
│   └── maccatalystpatches
├── store
├── tests
│   ├── e2e
│   ├── integration
│   └── unit
│       └── fixtures
├── theme
├── typings
└── windows
    └── bluewallet
        └── Assets
```

## Suggestion

It would be good to move these files and folders to `src` folder, only leave the configuration files in the root folder. It will be much clean and easier to manage the features and functionalities.

The folders and files can move to `src`:
```
- assets/fonts
- class
- components
- constants
- helpers
- img
- models
- screen
- store
- theme
- blueComponents.js
- Navigation.js
- NavigationService.js
- UnlockWith.js
```

**Comment by codewithmalik** [comment]
I will be working on it

**Comment by renie** [comment]
This seems to be a nice idea. But as it might generated lots of breaking changes, and will affect hundreds of files, it would be nice to have small and very specific PRs for that issue. That way it would be much easier to review and recheck tests[.
See more related data here.](https://github.com/mintlayer/mojito_mobile_wallet/pull/97#issuecomment-1669391404)
