### ISSUE TITLE
Extract `blue_module` and `class` to a separate SDK package 

### ISSUE THREAD

**Issue by macaroni7** [mintlayer/mojito_mobile_wallet#94]
There are many files inside `blue_module` and `class` folder are purely provide functionalities without React Native features, such as `class/wallet`, `multisig-cosigner.js`, `hd-segwit-bech32-transaction.js` etc.

To extract these functions to s separate SDK package can have several benefits:
- Make each function easy to test
- Easy to maintain these code base
- Provide clear API consumed by mobile app 
- Move these js code out of the mobile repo will make it easier to migrate the whole app code base to ts

**Comment by renie** [comment]
Agreed. Specially about making it easier to test and detachable. At same time we have lots of library updates and rebase to be done, which could cause rework related to this task if it was done before them.
I vote also for waiting for those tasks to be done, and then start this.
Opinions @owlsua ?
