### ISSUE TITLE
Use style framework to write styles in React Native

### ISSUE THREAD

**Issue by macaroni7** [mintlayer/mojito_mobile_wallet#95]
## Context

There has potential disadvantages of using StyleSheet in React Native include:

- Limited support for dynamic styling based on props or state.
- Limited set of styling properties compared to CSS.
- Difficulty in reusing styles across multiple components.

## Proposal

Consider to use style framework to write styles in React Native code bases. Some benefits to make the change:

- Clean style codes for components
- Easy to write reusable components

### Options

1. Tailwind CSS
These are some articles comparing the stylesheet with Tailwind for writing the style codes in RN:
- https://www.google.com/search?q=tailwind+with+react+native&oq=tailwind+with+react+native&aqs=chrome.0.0i512l2j0i20i263i512j0i512l6j0i390i650.11953j0j7&sourceid=chrome&ie=UTF-8
- https://geekyants.com/blog/using-tailwind-css-in-react-native/

2. Styled Components
- https://styled-components.com/docs/basics#react-native

**Comment by renie** [comment]
This is totally not a priority, as the lack of such a tools was never a problem for any developer that have ever worked on the repo. But I don't see any problem on discussing it. And personally I would vote for something simpler as Styled Components. Maybe it could even be discussed on the next layout change.
Any ideas on this @owlsua ?
