### ISSUE TITLE
Upgrade to latest React Native stable version: `v0.71.0`

### ISSUE THREAD

**Issue by macaroni7** [mintlayer/mojito_mobile_wallet#96]
The current RN version is `0.64.2` which was released in 2021 and a bit old.
It would be good to upgrade the React Native to the latest stable version `v0.71.0`

There has some significant changes with latest version:
- React 18
- [Hermes as default](https://blog.devgenius.io/whats-new-in-react-native-0-70-how-to-upgrade-and-why-it-matters-67aa35d75e37)
- Improvement for Android build process
- Debug tool upgrades
- Typescript by default

**Comment by renie** [comment]
I agree with the update, and actually it is something we should do soon. But as we have some more libraries to update, it might cause problems in many different parts such as tests not running properly, unexpected bugs, broken build process, broken development process any different OS/hardware, broken CI... Also now we have version 0.72, which also changes some libraries names and support. All of that might take days, or even more than a week to adjust and patch.
Of course that is all expected, but at the moment we are dealing with other priorities, also we have a limited workforce for this project. So for sure we are going to do this libraries update, it just might have to wait some more time.

And PR for this would be amazing.
