### ISSUE TITLE
Improve code readability with Absolute imports

### ISSUE THREAD

**Issue by amalikmuhd** [mintlayer/mojito_mobile_wallet#98]
I'd like to propose the implementation of absolute imports, It will improve the clarity of the code by making it simpler to identify the structure of the project. This small adjustment has the potential to make development smoother and reduce potential import-related challenges.

Before
```js
- import { BlueStorageContext } from './blue_modules/storage-context';
- import WidgetCommunication from './blue_modules/WidgetCommunication';
- import Privacy from './blue_modules/Privacy';
```
After
```js
+ import { BlueStorageContext } from 'blue_modules';
+ import WidgetCommunication from 'blue_modules';
+ import Privacy from 'blue_modules'

 or
 
+  import { BlueStorageContext , WidgetCommunication, Privacy } from 'blue_modules'
```

**Comment by renie** [comment]
I agree with this idea, but not just about blue_modules.
We could do something like what we have [on browser extension](https://github.com/mintlayer/mojito-browser-extension/blob/main/jsconfig.json). what do you think @owlsua ?

**Comment by amalikmuhd** [comment]
Good idea, when do we start working on it?
